-- CreateTable
CREATE TABLE "Libro" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" STRING NOT NULL,
    "Author" STRING NOT NULL,
    "Editorial" STRING NOT NULL,
    "Category" STRING,
    "AnoPublication" INT4 NOT NULL,
    "language" STRING,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Libro_pkey" PRIMARY KEY ("id")
);
